---
title: 'Applied Multivariate: Identifying differences between groups'
date: '2017-11-17'
categories: ["R"]
tags: ["Applied Multivariate"]
---



<pre class="r"><code>library(vegan) 
library(gridExtra)
library(tidyverse)</code></pre>
<div id="linear-discriminant-analysis" class="section level2">
<h2>Linear discriminant analysis</h2>
<ul>
<li><p>Often we have groups that we have defined <em>a priori</em> before doing an analysis and we seek to understand what makes those groups different</p></li>
<li><p>Linear discrimination analysis (LDA), similar to multinomial logistic regression, attempts to find linear combinations of variables that best separate groups when predicting two or more dependent variables, using continuous independent variables.</p></li>
</ul>
<div id="load-the-data" class="section level3">
<h3>Load the data</h3>
<p>We will use the data set <code>morph_data.csv</code> on <a href="">github</a>. The data consisted of 8 measurements in all 5
larval stages and the adults of the 6 species of the waterstrider
genus Limnoporus (Insecta: Heteroptera: Gerridae). Data was originally sourced from <a href="http://life.bio.sunysb.edu/morph/data/datasets.html">morphometry datasets</a>.</p>
<p>The variables are: Species, stage (1-5 for larvae, 6 for adults), sex (m male, f female, u undetermined), antseg1 - antseg4 (lengths of 1st to 4th antennal segments), midfem, midtib, hindfem, hindtib (lenghts of middle and hind femora and tibiae).
The values are raw measurements in millimeters.</p>
<pre class="r"><code>morph_data &lt;-read_csv(&quot;https://raw.githubusercontent.com/chrischizinski/SNR_R_Group/master/data/morph_data.csv&quot;)</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   Species = col_character(),
##   stage = col_integer(),
##   sex = col_character(),
##   antseg1 = col_double(),
##   antseg2 = col_double(),
##   antseg3 = col_double(),
##   antseg4 = col_double(),
##   midfem = col_double(),
##   midtib = col_double(),
##   hindfem = col_double(),
##   hindtib = col_double()
## )</code></pre>
<pre class="r"><code>glimpse(morph_data)</code></pre>
<pre><code>## Observations: 541
## Variables: 11
## $ Species &lt;chr&gt; &quot;canali&quot;, &quot;canali&quot;, &quot;canali&quot;, &quot;canali&quot;, &quot;canali&quot;, &quot;can...
## $ stage   &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, ...
## $ sex     &lt;chr&gt; &quot;u&quot;, &quot;u&quot;, &quot;u&quot;, &quot;u&quot;, &quot;u&quot;, &quot;u&quot;, &quot;u&quot;, &quot;u&quot;, &quot;u&quot;, &quot;u&quot;, &quot;u&quot;,...
## $ antseg1 &lt;dbl&gt; 0.17, 0.20, 0.18, 0.16, 0.13, 0.18, 0.18, 0.18, 0.20, ...
## $ antseg2 &lt;dbl&gt; 0.15, 0.14, 0.14, 0.13, 0.13, 0.16, 0.12, 0.15, 0.15, ...
## $ antseg3 &lt;dbl&gt; 0.19, 0.18, 0.17, 0.14, 0.16, 0.18, 0.16, 0.16, 0.19, ...
## $ antseg4 &lt;dbl&gt; 0.72, 0.74, 0.62, 0.55, 0.56, 0.52, 0.72, 0.60, 0.67, ...
## $ midfem  &lt;dbl&gt; 0.70, 0.76, 0.76, 0.70, 0.72, 0.76, 0.74, 0.76, 0.78, ...
## $ midtib  &lt;dbl&gt; 0.80, 0.92, 0.94, 0.92, 0.92, 0.97, 0.91, 0.92, 0.95, ...
## $ hindfem &lt;dbl&gt; 0.43, 0.68, 0.79, 0.74, 0.68, 0.68, 0.70, 0.70, 0.78, ...
## $ hindtib &lt;dbl&gt; 0.72, 0.42, 0.40, 0.42, 0.38, 0.45, 0.42, 0.43, 0.44, ...</code></pre>
</div>
<div id="manipulate-the-data" class="section level3">
<h3>Manipulate the data</h3>
<p>For the purpose of this excercise lets limit the data to one species and only the measurements of the antennae.</p>
<pre class="r"><code>morph_data %&gt;% 
  select(Species:antseg4, -sex) %&gt;% 
  filter(Species == &quot;canali&quot;) %&gt;% 
  mutate_at(vars(antseg1:antseg4), scale)-&gt; canal_data

head(canal_data)</code></pre>
<pre><code>## # A tibble: 6 x 6
##   Species stage antseg1 antseg2 antseg3 antseg4
##   &lt;chr&gt;   &lt;int&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
## 1 canali      1   -1.31   -1.33   -1.38   -1.27
## 2 canali      1   -1.26   -1.36   -1.42   -1.22
## 3 canali      1   -1.30   -1.36   -1.45   -1.51
## 4 canali      1   -1.33   -1.39   -1.55   -1.68
## 5 canali      1   -1.39   -1.39   -1.48   -1.65
## 6 canali      1   -1.30   -1.31   -1.42   -1.75</code></pre>
</div>
<div id="conduct-the-linear-discriminant-analysis-using-masslda" class="section level3">
<h3>Conduct the linear discriminant analysis using <code>MASS::lda()</code></h3>
<pre class="r"><code>canal_lda&lt;-MASS::lda(stage~antseg1 + antseg2 + antseg3 + antseg4, data = canal_data)

canal_lda</code></pre>
<pre><code>## Call:
## lda(stage ~ antseg1 + antseg2 + antseg3 + antseg4, data = canal_data)
## 
## Prior probabilities of groups:
##         1         2         3         4         5         6 
## 0.1111111 0.1111111 0.1111111 0.2222222 0.2222222 0.2222222 
## 
## Group means:
##      antseg1    antseg2    antseg3    antseg4
## 1 -1.3073501 -1.3594034 -1.4443907 -1.4868663
## 2 -1.1332171 -1.1490818 -1.1510214 -1.2348777
## 3 -0.8167818 -0.8640406 -0.8315750 -0.9156920
## 4 -0.3028084 -0.2399942 -0.1731241 -0.0805297
## 5  0.4283631  0.5487119  0.6043044  0.6886356
## 6  1.5031198  1.3775452  1.2823132  1.2106121
## 
## Coefficients of linear discriminants:
##                LD1        LD2        LD3       LD4
## antseg1 14.5047455 -7.2205800  3.8168030  2.764369
## antseg2 -3.8449898  1.2049129 -8.6374675 -2.428811
## antseg3 -1.7878986  0.9023135  4.3236873 -3.984543
## antseg4 -0.2461576  5.5171016  0.5203163  3.569601
## 
## Proportion of trace:
##    LD1    LD2    LD3    LD4 
## 0.9719 0.0276 0.0003 0.0002</code></pre>
<pre class="r"><code>names(canal_lda)</code></pre>
<pre><code>##  [1] &quot;prior&quot;   &quot;counts&quot;  &quot;means&quot;   &quot;scaling&quot; &quot;lev&quot;     &quot;svd&quot;     &quot;N&quot;      
##  [8] &quot;call&quot;    &quot;terms&quot;   &quot;xlevels&quot;</code></pre>
</div>
<div id="explanation-of-the-output" class="section level3">
<h3>Explanation of the output</h3>
<div id="prior" class="section level4">
<h4>Prior</h4>
<p>From the raw data, the break down in proportions of the number of individuals in each group</p>
<pre class="r"><code>canal_lda$prior</code></pre>
<pre><code>##         1         2         3         4         5         6 
## 0.1111111 0.1111111 0.1111111 0.2222222 0.2222222 0.2222222</code></pre>
</div>
<div id="group-means" class="section level4">
<h4>Group means</h4>
<p>The mean value for each of the variables for each group</p>
<pre class="r"><code>canal_lda$means</code></pre>
<pre><code>##      antseg1    antseg2    antseg3    antseg4
## 1 -1.3073501 -1.3594034 -1.4443907 -1.4868663
## 2 -1.1332171 -1.1490818 -1.1510214 -1.2348777
## 3 -0.8167818 -0.8640406 -0.8315750 -0.9156920
## 4 -0.3028084 -0.2399942 -0.1731241 -0.0805297
## 5  0.4283631  0.5487119  0.6043044  0.6886356
## 6  1.5031198  1.3775452  1.2823132  1.2106121</code></pre>
</div>
<div id="coefficients" class="section level4">
<h4>Coefficients</h4>
<p>These are the coffeicients to describe the linear discrimination. For example: LD1 = 14.5047455 x Group1 + -3.8449898 x Group2 + -1.7878986 x Group3 + …</p>
<pre class="r"><code>canal_lda$scaling</code></pre>
<pre><code>##                LD1        LD2        LD3       LD4
## antseg1 14.5047455 -7.2205800  3.8168030  2.764369
## antseg2 -3.8449898  1.2049129 -8.6374675 -2.428811
## antseg3 -1.7878986  0.9023135  4.3236873 -3.984543
## antseg4 -0.2461576  5.5171016  0.5203163  3.569601</code></pre>
<p>You can also standardize the coefficients (loadings), which provides the relative strength of each factor on linear discriminant analysis</p>
<pre class="r"><code>loadings &lt;-canal_lda$scaling
col.ss &lt;- colSums(loadings^2)
sweep(loadings,2,sqrt(col.ss),&quot;/&quot;)</code></pre>
<pre><code>##                 LD1         LD2         LD3        LD4
## antseg1  0.95969829 -0.78391461  0.36703621  0.4257438
## antseg2 -0.25440157  0.13081342 -0.83060701 -0.3740641
## antseg3 -0.11829530  0.09796121  0.41577985 -0.6136643
## antseg4 -0.01628688  0.59897356  0.05003531  0.5497585</code></pre>
</div>
</div>
<div id="variation-expained" class="section level3">
<h3>Variation expained</h3>
<p>The amount of variation explained by the each of the linear discriminant axis</p>
<pre class="r"><code>prop = canal_lda$svd^2/sum(canal_lda$svd^2)
prop</code></pre>
<pre><code>## [1] 0.9719389713 0.0275790703 0.0003069345 0.0001750239</code></pre>
</div>
<div id="graphing-the-results" class="section level3">
<h3>Graphing the results</h3>
<pre class="r"><code># extracting the data
lda_pred &lt;- predict(canal_lda)
lda_scores&lt;-data.frame(stage = lda_pred$class, lda_pred$x)

#developing hulls for each stage group

hull1&lt;- lda_scores[lda_scores$stage ==1,][chull(lda_scores[lda_scores$stage ==1,c(&quot;LD1&quot;, &quot;LD2&quot;)]),]
hull2&lt;- lda_scores[lda_scores$stage ==2,][chull(lda_scores[lda_scores$stage ==2,c(&quot;LD1&quot;, &quot;LD2&quot;)]),]
hull3&lt;- lda_scores[lda_scores$stage ==3,][chull(lda_scores[lda_scores$stage ==3,c(&quot;LD1&quot;, &quot;LD2&quot;)]),]
hull4&lt;- lda_scores[lda_scores$stage ==4,][chull(lda_scores[lda_scores$stage ==4,c(&quot;LD1&quot;, &quot;LD2&quot;)]),]
hull5&lt;- lda_scores[lda_scores$stage ==5,][chull(lda_scores[lda_scores$stage ==5,c(&quot;LD1&quot;, &quot;LD2&quot;)]),]
hull6&lt;- lda_scores[lda_scores$stage ==6,][chull(lda_scores[lda_scores$stage ==6,c(&quot;LD1&quot;, &quot;LD2&quot;)]),]

all_hulls &lt;- rbind(hull1, hull2, hull3, hull4, hull5, hull6)

#plot using gglot2

ggplot(data = lda_scores) + 
  geom_point(aes(x = LD1, y = LD2, color = stage), size = 2) +
  geom_polygon(data = all_hulls,aes(x = LD1, y = LD2, color = stage, fill = stage), alpha = 0.25) +
  coord_equal() + 
  theme_classic()</code></pre>
<p><img src="/post/2017-11-17-Differencesbetweengroups_files/figure-html/unnamed-chunk-10-1.png" width="576" /></p>
</div>
<div id="assessing-the-accuracy-of-the-predicitions" class="section level3">
<h3>Assessing the accuracy of the predicitions</h3>
<pre class="r"><code>ct &lt;- table(canal_data$stage, lda_pred$class)
ct</code></pre>
<pre><code>##    
##      1  2  3  4  5  6
##   1  9  1  0  0  0  0
##   2  0 10  0  0  0  0
##   3  0  0 10  0  0  0
##   4  0  0  0 20  0  0
##   5  0  0  0  0 20  0
##   6  0  0  0  0  0 20</code></pre>
<pre class="r"><code># percent correct for each stage
diag(prop.table(ct, 1))</code></pre>
<pre><code>##   1   2   3   4   5   6 
## 0.9 1.0 1.0 1.0 1.0 1.0</code></pre>
<pre class="r"><code># total percent correct
sum(diag(prop.table(ct)))</code></pre>
<pre><code>## [1] 0.9888889</code></pre>
</div>
</div>
<div id="manova-and-mancova" class="section level2">
<h2>MANOVA and MANCOVA</h2>
<p>Two common multivariate regression models are the multivariate analysis of variance (MANOVA; an extension of the univariate ANOVA) when all predictor variables are categorical, and the multivariate analysis of covariance (MANCOVA; extension of univariate ANCOVA) when predictor variables are categorical and continuous.</p>
<div id="load-the-data-1" class="section level3">
<h3>Load the data</h3>
<pre class="r"><code>bryc_data &lt;- read.table(&quot;http://ecology.msu.montana.edu/labdsv/R/labs/lab1/bryceveg.R&quot;)


bryc_data %&gt;% rownames_to_column(&quot;site&quot;) -&gt; bryc_data

bryc_site_data &lt;- read.table(&quot;http://ecology.msu.montana.edu/labdsv/R/labs/lab2/brycesite.R&quot;)

bryc_site_data %&gt;% 
  rownames_to_column(&quot;site&quot;) %&gt;% 
  full_join(bryc_data, by = &quot;site&quot;) -&gt; bryc_site_data

glimpse(bryc_site_data)</code></pre>
<pre><code>## Observations: 160
## Variables: 182
## $ site     &lt;chr&gt; &quot;bcnp__1&quot;, &quot;bcnp__2&quot;, &quot;bcnp__3&quot;, &quot;bcnp__4&quot;, &quot;bcnp__5&quot;...
## $ plotcode &lt;int&gt; 50001, 50002, 50003, 50004, 50005, 50006, 50007, 5000...
## $ annrad   &lt;int&gt; 241, 222, 231, 254, 232, 216, 288, 279, 187, 279, 271...
## $ asp      &lt;int&gt; 30, 50, 50, 360, 300, 330, 150, 220, 360, 125, 125, 2...
## $ av       &lt;dbl&gt; 1.00, 0.96, 0.96, 0.93, 0.48, 0.76, 0.25, 0.00, 0.93,...
## $ depth    &lt;chr&gt; &quot;deep&quot;, &quot;shallow&quot;, &quot;shallow&quot;, &quot;shallow&quot;, &quot;shallow&quot;, &quot;...
## $ east     &lt;dbl&gt; 388220.9, 388477.2, 388384.0, 388307.5, 389026.3, 389...
## $ elev     &lt;int&gt; 8720, 8360, 8560, 8660, 8480, 8560, 8560, 8680, 8240,...
## $ grorad   &lt;int&gt; 162, 156, 159, 166, 159, 155, 169, 169, 146, 167, 168...
## $ north    &lt;int&gt; 4144784, 4147573, 4147347, 4146971, 4146846, 4146853,...
## $ pos      &lt;chr&gt; &quot;ridge&quot;, &quot;mid_slope&quot;, &quot;mid_slope&quot;, &quot;ridge&quot;, &quot;up_slope...
## $ quad     &lt;chr&gt; &quot;pc&quot;, &quot;pc&quot;, &quot;pc&quot;, &quot;pc&quot;, &quot;pc&quot;, &quot;pc&quot;, &quot;pc&quot;, &quot;pc&quot;, &quot;bp&quot;,...
## $ slope    &lt;int&gt; 9, 2, 2, 0, 2, 2, 3, 2, 3, 3, 2, 6, 3, 4, 3, 4, 2, 1,...
## $ junost   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ ameuta   &lt;dbl&gt; 0.0, 0.5, 0.0, 0.5, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0...
## $ arcpat   &lt;dbl&gt; 1.0, 0.5, 1.0, 1.0, 4.0, 1.0, 4.0, 2.0, 0.0, 5.0, 2.0...
## $ arttri   &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...
## $ atrcan   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ berfre   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ ceamar   &lt;dbl&gt; 0.5, 0.0, 0.5, 0.5, 0.5, 1.0, 1.0, 0.0, 0.0, 0.5, 0.5...
## $ cerled   &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5...
## $ cermon   &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...
## $ chrdep   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ chrnau   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ chrpar   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ chrvis   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ eurlan   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ juncom   &lt;dbl&gt; 0.0, 2.0, 1.0, 0.0, 1.0, 0.5, 0.0, 0.5, 0.5, 0.0, 0.0...
## $ pacmyr   &lt;dbl&gt; 0.0, 0.5, 0.5, 0.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.0, 0.5...
## $ pruvir   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ purtri   &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.5, 0.5, 0.5, 0.0, 0.0, 1.0, 1.0...
## $ quegam   &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...
## $ rhutri   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ ribcer   &lt;dbl&gt; 0.0, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5...
## $ roswoo   &lt;dbl&gt; 0.0, 0.5, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...
## $ samcoe   &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...
## $ shearg   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ sherot   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ symore   &lt;dbl&gt; 1.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5...
## $ arcuva   &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ artarb   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ artfri   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ artpyg   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ atrcon   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ berrep   &lt;dbl&gt; 1.0, 0.0, 0.5, 1.0, 0.5, 1.0, 0.5, 0.0, 1.0, 0.5, 1.0...
## $ ericor   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ gutsar   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ tetcan   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ agrcri   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ agrdas   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ agrscr   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ agrsmi   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ bougra   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ broano   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ brocil   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ broine   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ carrss   &lt;dbl&gt; 0.5, 0.5, 0.5, 0.5, 1.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5...
## $ elysal   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ fesovi   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ hiljam   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ junbal   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ koenit   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ muhmon   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ muhric   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ oryhym   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ orymic   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ phlpra   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ poacom   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ poafen   &lt;dbl&gt; 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...
## $ poanev   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ poapra   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ sithys   &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.0...
## $ sticom   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ stilet   &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5...
## $ stipin   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ achmil   &lt;dbl&gt; 0.0, 0.5, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5...
## $ agogla   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ anemul   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ antros   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ antros.1 &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5...
## $ apoand   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ arahol   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ arapen   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ arefen   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ artcar   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ artlud   &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...
## $ astagr   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ astchi   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ astcon   &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.0...
## $ asthum   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ astken   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ astmeg   &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...
## $ astmis   &lt;dbl&gt; 0.5, 0.0, 0.0, 0.0, 0.5, 0.0, 0.5, 0.5, 0.5, 0.0, 0.0...
## $ astten   &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...
## $ balsag   &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...
## $ calnut   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ caschr   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ caslin   &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.5, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0...
## $ chadou   &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5...
## $ cirneo   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ compal   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ corkin   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ creint   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ crycon   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ cympur   &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...
## $ dessop   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ drasub   &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.0...
## $ echtri   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ eriala   &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...
## $ erican   &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5...
## $ erieat   &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5...
## $ erifla   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ eripan   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ eripum   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ erirac   &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...
## $ erisub   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ eriumb   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ eupfen   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ euplur   &lt;dbl&gt; 0.0, 0.5, 0.0, 0.0, 0.5, 0.0, 0.5, 0.5, 0.0, 0.5, 0.0...
## $ euprob   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ fraves   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ genaff   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ gerfre   &lt;dbl&gt; 0.5, 0.5, 0.5, 0.0, 0.0, 0.5, 0.0, 0.0, 0.5, 0.0, 0.0...
## $ gerric   &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...
## $ gilcon   &lt;dbl&gt; 0.0, 0.5, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...
## $ haparm   &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...
## $ heddru   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ hymaca   &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...
## $ hymfil   &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...
## $ hymric   &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5...
## $ ipoagg   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ irimis   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ ivesab   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ leppun   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ lesint   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ leueri   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ ligpor   &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ linkin   &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...
## $ linlew   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ litinc   &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...
## $ litmul   &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.5...
## $ lotuta   &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...
## $ lupkin   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ lupser   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ lyggra   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ lygspi   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ macgri   &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.0...
## $ molpar   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ oenbra   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ oencae   &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...
## $ oencor   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ oenfla   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ oenlav   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ opueri   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ orofas   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ pedcan   &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.5, 0.0, 0.5, 0.0, 0.0, 0.5, 0.0...
## $ pedsim   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ pencae   &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.5...
## $ pencom   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ penlei   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ penuta   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ phllon   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ phycha   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ potcon   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ potcri   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ potgra   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ pteand   &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.0...
## $ pyrvir   &lt;dbl&gt; 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0...
## $ salibe   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ sclwhi   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ senmul   &lt;dbl&gt; 0.0, 0.5, 0.5, 0.5, 0.5, 0.0, 0.5, 0.5, 0.0, 0.5, 0.5...
## $ sphcoc   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ stapin   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ steten   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ strcor   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ swerad   &lt;dbl&gt; 0.0, 0.5, 0.0, 0.0, 0.5, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0...
## $ taroff   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ thafen   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ towmin   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ tradub   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ valacu   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
## $ vicame   &lt;dbl&gt; 0.0, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...</code></pre>
</div>
<div id="using-manova-and-mancova" class="section level3">
<h3>Using MANOVA and MANCOVA</h3>
</div>
<div id="manova" class="section level3">
<h3>MANOVA</h3>
<p>-Independent variable is a categorical variable
- Interpret like ANOVA
- degfault test statistic is “Pillai” but “Wilks”, “Hotelling-Lawley”, “Roy” are also available. See <code>?summary.manova</code>. Wilks’ statistic is most popular in the literature, but the default Pillai–Bartlett statistic is recommended by <a href="https://www.crcpress.com/Multivariate-Analysis-of-Variance-and-Repeated-Measures-A-Practical-Approach/Hand-Taylor/p/book/9780412258008">Hand and Taylor (1987)</a></p>
<p>As a <strong>reminder</strong>:</p>
<p>-R provides Type I sequential SS, not the default Type III marginal SS reported by SAS and SPSS. In a nonorthogonal design with more than one term on the right hand side of the equation order will matter (i.e., A+B and B+A will produce different results)!
- Type I sequential SS: tests the main effect of factor A, followed by the main effect of factor B after the main effect of A, followed by the interaction effect AB after the main effects.
- Type II: tests for each main effect after the other main effect. No significant interaction is assumed (in other words, you should test for interaction first (SS(AB | A, B)) and only if AB is not significant, continue with the analysis for main effects).
- Type III: tests for the presence of a main effect after the other main effect and interaction. This approach is therefore valid in the presence of significant interactions. If the interactions are not significant, type II gives a more powerful test.</p>
<ul>
<li><p>NOTE: when data is balanced, the factors are orthogonal, and types I, II and III all give the same results.</p></li>
<li><p>If you wish to find ways to produce Type II or III SS then you will need to find a package to help. For example, <code>regr0</code> has a <code>drop1()</code> function for <code>mlm</code> models. Install via <code>install.packages(&quot;regr0&quot;, repos=&quot;http://R-Forge.R-project.org&quot;)</code></p></li>
</ul>
<pre class="r"><code>man_out &lt;- manova(cbind(junost,ameuta,arcpat,arttri,atrcan) ~ pos,data = bryc_site_data)
summary(man_out)</code></pre>
<pre><code>##            Df  Pillai approx F num Df den Df  Pr(&gt;F)  
## pos         4 0.18304    1.477     20    616 0.08253 .
## Residuals 155                                         
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
<div id="mancova" class="section level3">
<h3>MANCOVA</h3>
<ul>
<li>When you have a categorical and continuous independent variables</li>
</ul>
<pre class="r"><code>man_out &lt;- manova(cbind(arcpat, artarb, carrss, purtri,sticom) ~ pos + elev, data = bryc_site_data)
summary(man_out)</code></pre>
<pre><code>##            Df Pillai approx F num Df den Df    Pr(&gt;F)    
## pos         4 0.2700   2.2150     20    612 0.0018133 ** 
## elev        1 0.1438   5.0387      5    150 0.0002688 ***
## Residuals 154                                            
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
</div>
<div id="anosim" class="section level2">
<h2>ANOSIM</h2>
<p>Analysis of similarities (ANOSIM) provides a way to test statistically whether there is a significant difference between two or more groups of sampling units.</p>
<p>The R-statistic in ANOSIM is a ratio between within-group and between-group dissimilarities</p>
<pre class="r"><code># create the y variable 
y&lt;-cbind(bryc_site_data$arcpat,bryc_site_data$artarb,bryc_site_data$carrss,bryc_site_data$purtri,bryc_site_data$sticom)

# convert to an x variable
x &lt;- as.factor(bryc_site_data$pos)

# analysis
anosim_out &lt;- anosim(y, x, distance = &quot;euclidean&quot;, permutations = 999)
summary(anosim_out)</code></pre>
<pre><code>## 
## Call:
## anosim(x = y, grouping = x, permutations = 999, distance = &quot;euclidean&quot;) 
## Dissimilarity: euclidean 
## 
## ANOSIM statistic R: 0.0162 
##       Significance: 0.206 
## 
## Permutation: free
## Number of permutations: 999
## 
## Upper quantiles of permutations (null model):
##    90%    95%  97.5%    99% 
## 0.0287 0.0403 0.0498 0.0593 
## 
## Dissimilarity ranks between and within classes:
##            0%     25%     50%       75%    100%    N
## Between   198 2978.50 6359.50  9536.000 12720.0 9823
## bottom    198 4155.00 6932.50  9591.125 12485.0  190
## low_slope 198 4070.00 6876.75 10634.500 12716.5  528
## mid_slope 198 3220.75 7323.50 10180.000 12704.0 1431
## ridge     198 2978.50 6196.50  8470.000 11827.5  153
## up_slope  198 1628.50 3863.50  6932.500 11978.0  595</code></pre>
<pre class="r"><code>perms&lt;-permustats(anosim_out)
summary(perms)</code></pre>
<pre><code>## 
##   statistic     SES    mean lower  median   upper Pr(perm)
## R    0.0162  0.7756 -0.0008       -0.0028  0.0403    0.206
## 
## (Interval (Upper - Lower) = 0.95)</code></pre>
<pre class="r"><code>densityplot(perms)</code></pre>
<p><img src="/post/2017-11-17-Differencesbetweengroups_files/figure-html/unnamed-chunk-15-1.png" width="576" /></p>
<pre class="r"><code>anosim_out$perm</code></pre>
<pre><code>##            TRUE            TRUE            TRUE            TRUE 
## -0.001145157096 -0.006668393000 -0.009010047394 -0.020255730433 
##            TRUE            TRUE            TRUE            TRUE 
## -0.021096571202 -0.010140164375 -0.005727577641  0.026860202948 
##            TRUE            TRUE            TRUE            TRUE 
## -0.001537008291 -0.013828682067 -0.012435503651 -0.016695440256 
##            TRUE            TRUE            TRUE            TRUE 
##  0.031666468182  0.013505108772  0.007307141022 -0.020459017956 
##            TRUE            TRUE            TRUE            TRUE 
## -0.030762480018  0.026057559852  0.000859851754  0.003411294655 
##            TRUE            TRUE            TRUE            TRUE 
##  0.006235322052  0.023775081982  0.003323092117 -0.005630695411 
##            TRUE            TRUE            TRUE            TRUE 
## -0.033832912275 -0.008987838627 -0.017780015209 -0.012095660326 
##            TRUE            TRUE            TRUE            TRUE 
## -0.013577814370  0.029303061847  0.016304889256 -0.009911189181 
##            TRUE            TRUE            TRUE            TRUE 
## -0.002444967327  0.001729859100  0.005871126393 -0.011300396725 
##            TRUE            TRUE            TRUE            TRUE 
##  0.009878508559 -0.038084344889 -0.017889583143  0.058057300094 
##            TRUE            TRUE            TRUE            TRUE 
## -0.038579052192 -0.029182143547 -0.031059873675 -0.003227228960 
##            TRUE            TRUE            TRUE            TRUE 
## -0.007943358930  0.061255924724  0.002415554767 -0.000950408703 
##            TRUE            TRUE            TRUE            TRUE 
##  0.037174101725  0.008845344088 -0.000444561876 -0.026649465649 
##            TRUE            TRUE            TRUE            TRUE 
## -0.013596825355  0.027407164105  0.002091876051 -0.014137144967 
##            TRUE            TRUE            TRUE            TRUE 
##  0.008196967583  0.004086940152  0.022336677803 -0.005891191592 
##            TRUE            TRUE            TRUE            TRUE 
## -0.003252248963  0.024975374449 -0.009008395792  0.011402550023 
##            TRUE            TRUE            TRUE            TRUE 
## -0.032702654731 -0.021983586527  0.006772760147  0.001896741113 
##            TRUE            TRUE            TRUE            TRUE 
##  0.024537137854 -0.040356210342  0.003342489647 -0.020510358158 
##            TRUE            TRUE            TRUE            TRUE 
##  0.000728250756  0.016666589943  0.002954890446  0.011090151392 
##            TRUE            TRUE            TRUE            TRUE 
## -0.000068945570  0.000337067229 -0.010056670658 -0.011834953302 
##            TRUE            TRUE            TRUE            TRUE 
##  0.008991914920  0.006352023498  0.009130473727 -0.035994296142 
##            TRUE            TRUE            TRUE            TRUE 
## -0.014370055892  0.039894394504  0.016761328606  0.017663770590 
##            TRUE            TRUE            TRUE            TRUE 
##  0.021098433646 -0.035296828423 -0.001303253995 -0.002225269212 
##            TRUE            TRUE            TRUE            TRUE 
## -0.005084577625  0.030609935310  0.026502086587 -0.012311703834 
##            TRUE            TRUE            TRUE            TRUE 
##  0.011030412622 -0.001152466310  0.014726098966 -0.001868769312 
##            TRUE            TRUE            TRUE            TRUE 
## -0.016536218861 -0.008976558541  0.001921023166  0.002086183297 
##            TRUE            TRUE            TRUE            TRUE 
## -0.003798155906  0.045266280475 -0.013016656469 -0.006218138371 
##            TRUE            TRUE            TRUE            TRUE 
## -0.017131744125  0.009414689715  0.015754765458 -0.013410018705 
##            TRUE            TRUE            TRUE            TRUE 
## -0.008305024477 -0.018203211690 -0.010733300088 -0.014569477965 
##            TRUE            TRUE            TRUE            TRUE 
## -0.028855196769  0.038307838173 -0.022810441395 -0.001767881070 
##            TRUE            TRUE            TRUE            TRUE 
## -0.023314601480 -0.006306059785  0.021758371361  0.050965148366 
##            TRUE            TRUE            TRUE            TRUE 
##  0.041442928864  0.000343779056  0.065237689500 -0.009609859793 
##            TRUE            TRUE            TRUE            TRUE 
##  0.023359335278  0.019136893537 -0.020716140653 -0.013701016800 
##            TRUE            TRUE            TRUE            TRUE 
##  0.023084677494  0.018616428281  0.032170241722 -0.012589735101 
##            TRUE            TRUE            TRUE            TRUE 
## -0.012116744598 -0.002844162877  0.011614025272  0.012811365941 
##            TRUE            TRUE            TRUE            TRUE 
## -0.028050902071 -0.030686928043 -0.027126989270 -0.009822354114 
##            TRUE            TRUE            TRUE            TRUE 
##  0.027577946709 -0.028492512149  0.025153114862  0.005478291265 
##            TRUE            TRUE            TRUE            TRUE 
## -0.032946142933  0.036182508411  0.000197313646  0.026403341913 
##            TRUE            TRUE            TRUE            TRUE 
## -0.007474515001 -0.003873989005 -0.022232134954 -0.010778947537 
##            TRUE            TRUE            TRUE            TRUE 
##  0.015819564454 -0.009744447729  0.020102342354  0.005718933089 
##            TRUE            TRUE            TRUE            TRUE 
## -0.003158915918 -0.006351180127 -0.000523803598 -0.027176923855 
##            TRUE            TRUE            TRUE            TRUE 
##  0.035275287325 -0.021158242698 -0.003966970644  0.000197313646 
##            TRUE            TRUE            TRUE            TRUE 
##  0.001077792846 -0.020521849086 -0.007922063816 -0.009946891881 
##            TRUE            TRUE            TRUE            TRUE 
##  0.041826697756 -0.020860813900  0.012396216624  0.004192185810 
##            TRUE            TRUE            TRUE            TRUE 
## -0.026903495987 -0.004505006127 -0.013874926903  0.030660853827 
##            TRUE            TRUE            TRUE            TRUE 
##  0.002998534889  0.016547815211 -0.016128519321 -0.000904655832 
##            TRUE            TRUE            TRUE            TRUE 
##  0.095530447077 -0.001923272155  0.004610778891 -0.007431784210 
##            TRUE            TRUE            TRUE            TRUE 
## -0.025120258538 -0.034301229097  0.011154388141  0.002506744244 
##            TRUE            TRUE            TRUE            TRUE 
## -0.008262328826 -0.023816723419  0.033911556609 -0.010336107543 
##            TRUE            TRUE            TRUE            TRUE 
## -0.012725342111 -0.029795133616 -0.009640783392  0.045954049429 
##            TRUE            TRUE            TRUE            TRUE 
## -0.020593781595 -0.014178680983  0.009837077964  0.004682043731 
##            TRUE            TRUE            TRUE            TRUE 
##  0.000065115260 -0.020331633812  0.002799921046  0.024928953910 
##            TRUE            TRUE            TRUE            TRUE 
## -0.034725796055 -0.012750010709 -0.016944269806  0.020058557349 
##            TRUE            TRUE            TRUE            TRUE 
## -0.034473593021 -0.011882849740 -0.037174558551  0.034534034601 
##            TRUE            TRUE            TRUE            TRUE 
## -0.027022692405 -0.019063274287 -0.018525625350  0.064409710137 
##            TRUE            TRUE            TRUE            TRUE 
## -0.019925023626  0.055367825492 -0.025080760669  0.003733954298 
##            TRUE            TRUE            TRUE            TRUE 
##  0.014747921187 -0.035631119556 -0.000499451264 -0.041051218230 
##            TRUE            TRUE            TRUE            TRUE 
##  0.012389926483 -0.017458198937  0.014043390237  0.023877516403 
##            TRUE            TRUE            TRUE            TRUE 
##  0.003509195958 -0.002818896891  0.048299323290 -0.034950870659 
##            TRUE            TRUE            TRUE            TRUE 
##  0.004667109038 -0.001752419271  0.020724539222 -0.004922720696 
##            TRUE            TRUE            TRUE            TRUE 
## -0.009217094945  0.012013572227  0.047115406274 -0.033383325314 
##            TRUE            TRUE            TRUE            TRUE 
##  0.048359343184  0.042721900806  0.003634085129 -0.031177383351 
##            TRUE            TRUE            TRUE            TRUE 
##  0.034972622600  0.002173261341  0.012593635691 -0.013765675234 
##            TRUE            TRUE            TRUE            TRUE 
##  0.001314534081  0.007928248535 -0.032326651880  0.000279682869 
##            TRUE            TRUE            TRUE            TRUE 
##  0.034675966892 -0.030109429832 -0.025959623408 -0.003327027848 
##            TRUE            TRUE            TRUE            TRUE 
## -0.032930083746  0.005129803388 -0.024183941157 -0.027924255877 
##            TRUE            TRUE            TRUE            TRUE 
##  0.000732151347  0.012040454674 -0.018455485005 -0.009939688088 
##            TRUE            TRUE            TRUE            TRUE 
## -0.020810000804  0.009936595729 -0.015443456182 -0.011910786401 
##            TRUE            TRUE            TRUE            TRUE 
## -0.016354823841 -0.004693675221  0.005410259347  0.013675539971 
##            TRUE            TRUE            TRUE            TRUE 
##  0.041765061400 -0.000766026744  0.008391715975 -0.025600558255 
##            TRUE            TRUE            TRUE            TRUE 
## -0.003960891346 -0.010757933546 -0.001326411554 -0.014762750459 
##            TRUE            TRUE            TRUE            TRUE 
##  0.001463705306 -0.008638331677 -0.019689793431 -0.026117720308 
##            TRUE            TRUE            TRUE            TRUE 
## -0.010106288978  0.001339237820  0.000339386499 -0.039021892186 
##            TRUE            TRUE            TRUE            TRUE 
## -0.022372556205  0.000290857533  0.015644670418  0.026740549704 
##            TRUE            TRUE            TRUE            TRUE 
## -0.003592478833  0.003369793779  0.008071902709 -0.034641634669 
##            TRUE            TRUE            TRUE            TRUE 
## -0.011034559195  0.043800291040  0.003887307237 -0.001251667810 
##            TRUE            TRUE            TRUE            TRUE 
## -0.018241128239 -0.023110435446 -0.011291049365 -0.006856956673 
##            TRUE            TRUE            TRUE            TRUE 
##  0.011011401636  0.001496385927  0.000433773757  0.002610795126 
##            TRUE            TRUE            TRUE            TRUE 
##  0.000183573729  0.004839543243 -0.020698781269  0.062038854026 
##            TRUE            TRUE            TRUE            TRUE 
## -0.027574538085 -0.005145792294  0.001343349253  0.059326292147 
##            TRUE            TRUE            TRUE            TRUE 
## -0.021279688105 -0.011505300709  0.017128019237 -0.015381468422 
##            TRUE            TRUE            TRUE            TRUE 
## -0.016652112077 -0.010159737608  0.011299237090  0.031527944514 
##            TRUE            TRUE            TRUE            TRUE 
## -0.008454230842  0.025323054095 -0.010722055143 -0.023082955612 
##            TRUE            TRUE            TRUE            TRUE 
##  0.001030107251 -0.003123072656 -0.011899787439  0.035259825526 
##            TRUE            TRUE            TRUE            TRUE 
##  0.017014375011  0.003429110865  0.001989230786  0.007326011445 
##            TRUE            TRUE            TRUE            TRUE 
##  0.001461596878  0.001121191306 -0.019304513500 -0.011363403558 
##            TRUE            TRUE            TRUE            TRUE 
##  0.024176667083 -0.053269940424  0.001195935051  0.026991311980 
##            TRUE            TRUE            TRUE            TRUE 
## -0.025510422992 -0.028935633267  0.001077265740 -0.024103047833 
##            TRUE            TRUE            TRUE            TRUE 
## -0.017455036296 -0.002235213960  0.008101596392 -0.014459910031 
##            TRUE            TRUE            TRUE            TRUE 
##  0.003498056434 -0.013731518713 -0.001884125690 -0.025462983380 
##            TRUE            TRUE            TRUE            TRUE 
## -0.015143426990  0.008519240681  0.036317939718 -0.037995861228 
##            TRUE            TRUE            TRUE            TRUE 
## -0.017398987273 -0.021156872220 -0.008815017877 -0.018973385007 
##            TRUE            TRUE            TRUE            TRUE 
## -0.036730172377  0.006753924864  0.012594830467  0.017827595383 
##            TRUE            TRUE            TRUE            TRUE 
##  0.006773673798 -0.028659605005  0.013543306445 -0.009143897381 
##            TRUE            TRUE            TRUE            TRUE 
##  0.024811022548 -0.019515672484  0.014327641365 -0.004987238569 
##            TRUE            TRUE            TRUE            TRUE 
## -0.024912508178 -0.001045850174 -0.002230715982 -0.023901165929 
##            TRUE            TRUE            TRUE            TRUE 
##  0.000385455633  0.029565771877 -0.037856880734  0.014605988896 
##            TRUE            TRUE            TRUE            TRUE 
## -0.002218416823 -0.017211337252  0.013703722614  0.024248213046 
##            TRUE            TRUE            TRUE            TRUE 
## -0.003137655944  0.010248888938  0.017626556849 -0.027452670992 
##            TRUE            TRUE            TRUE            TRUE 
## -0.030578098059  0.027978407316  0.042400225096 -0.018604937353 
##            TRUE            TRUE            TRUE            TRUE 
## -0.014372691426  0.015115771454 -0.036174039561 -0.025580352495 
##            TRUE            TRUE            TRUE            TRUE 
##  0.060499561605 -0.028225058158  0.023783234567  0.003737362922 
##            TRUE            TRUE            TRUE            TRUE 
## -0.035835355871 -0.021650314467 -0.003237208849  0.004844216923 
##            TRUE            TRUE            TRUE            TRUE 
##  0.039301856178 -0.015985743659 -0.010400344292 -0.018648792639 
##            TRUE            TRUE            TRUE            TRUE 
##  0.048879000209 -0.033701978945 -0.037082666265  0.009334991166 
##            TRUE            TRUE            TRUE            TRUE 
##  0.011328825352 -0.016039157148  0.015074235438 -0.005513396577 
##            TRUE            TRUE            TRUE            TRUE 
## -0.012337391505  0.014229002112  0.032773216762  0.001256903737 
##            TRUE            TRUE            TRUE            TRUE 
## -0.004329022736  0.009323113693  0.015931978765 -0.000731624240 
##            TRUE            TRUE            TRUE            TRUE 
## -0.028295444486 -0.013699751743  0.003177118673 -0.004378500494 
##            TRUE            TRUE            TRUE            TRUE 
## -0.022364684744 -0.003108700211 -0.010693942780 -0.047735564996 
##            TRUE            TRUE            TRUE            TRUE 
## -0.012745618152  0.024369096206 -0.029917070990 -0.018347006425 
##            TRUE            TRUE            TRUE            TRUE 
## -0.001931003055  0.000543657955 -0.023974187791 -0.030494569201 
##            TRUE            TRUE            TRUE            TRUE 
##  0.029908883264  0.016337359035 -0.030698313550 -0.000648798191 
##            TRUE            TRUE            TRUE            TRUE 
## -0.016171285253  0.036504992352  0.051017542782 -0.003039332955 
##            TRUE            TRUE            TRUE            TRUE 
##  0.043088837421  0.017600939459 -0.038086312755 -0.007125535158 
##            TRUE            TRUE            TRUE            TRUE 
## -0.003927718758 -0.005885779962  0.011721344217 -0.014996891300 
##            TRUE            TRUE            TRUE            TRUE 
## -0.023042368388 -0.012560849648  0.005298969531 -0.017142637666 
##            TRUE            TRUE            TRUE            TRUE 
## -0.039071545647  0.002032242701 -0.018143578340  0.040736359767 
##            TRUE            TRUE            TRUE            TRUE 
## -0.007981416041 -0.003150903895 -0.011499467394  0.023845608872 
##            TRUE            TRUE            TRUE            TRUE 
##  0.030392591605  0.041623831918 -0.005058468268  0.025254213947 
##            TRUE            TRUE            TRUE            TRUE 
## -0.022397611349  0.028337859014 -0.014881138646  0.014994396328 
##            TRUE            TRUE            TRUE            TRUE 
## -0.005768867674 -0.008354818499  0.030048882831 -0.015870728955 
##            TRUE            TRUE            TRUE            TRUE 
## -0.020120123423  0.017964151185  0.004907012914  0.056666124684 
##            TRUE            TRUE            TRUE            TRUE 
##  0.016566966758  0.020840397297  0.016749310571  0.016712483375 
##            TRUE            TRUE            TRUE            TRUE 
##  0.011119880216 -0.030438660740  0.019842865246  0.017258460600 
##            TRUE            TRUE            TRUE            TRUE 
## -0.027546671705 -0.020617501401  0.013702879244 -0.008630108811 
##            TRUE            TRUE            TRUE            TRUE 
##  0.008780650514 -0.017539724789 -0.007984543542 -0.001316115401 
##            TRUE            TRUE            TRUE            TRUE 
##  0.026503105661 -0.000733205560  0.009565863945  0.044075054245 
##            TRUE            TRUE            TRUE            TRUE 
##  0.029151957898  0.034233267460  0.018568848108 -0.001602545237 
##            TRUE            TRUE            TRUE            TRUE 
##  0.058017802224  0.015332869175  0.000045366325 -0.023663054216 
##            TRUE            TRUE            TRUE            TRUE 
##  0.028902390398  0.024500310659 -0.003752754441 -0.009955501292 
##            TRUE            TRUE            TRUE            TRUE 
## -0.019074378670  0.006077963102 -0.034094849214 -0.014476039499 
##            TRUE            TRUE            TRUE            TRUE 
## -0.030368555535  0.017128476063 -0.023312282210 -0.003751524525 
##            TRUE            TRUE            TRUE            TRUE 
##  0.016737503378  0.025327306090  0.004974025758 -0.035995315215 
##            TRUE            TRUE            TRUE            TRUE 
##  0.028103964156  0.027215262089 -0.008856553893 -0.013895765192 
##            TRUE            TRUE            TRUE            TRUE 
## -0.041079190031 -0.000646654624  0.018098528279 -0.003790776411 
##            TRUE            TRUE            TRUE            TRUE 
##  0.015806351644 -0.005511358431 -0.016820083444 -0.023816407155 
##            TRUE            TRUE            TRUE            TRUE 
## -0.011533377931  0.010177729520  0.060446815785 -0.018495755964 
##            TRUE            TRUE            TRUE            TRUE 
## -0.005592462598 -0.001933568308 -0.031597557753  0.014482189079 
##            TRUE            TRUE            TRUE            TRUE 
##  0.055265250509 -0.035965059285  0.021004678916 -0.028058492409 
##            TRUE            TRUE            TRUE            TRUE 
## -0.022754286951  0.024662202728 -0.036441177288 -0.006559176471 
##            TRUE            TRUE            TRUE            TRUE 
## -0.017791576419 -0.009678559379 -0.000521730312  0.001910867575 
##            TRUE            TRUE            TRUE            TRUE 
##  0.016209518066 -0.007780658631  0.000577006245 -0.006554994757 
##            TRUE            TRUE            TRUE            TRUE 
## -0.023987084337 -0.000006255001 -0.004459323537  0.006774692872 
##            TRUE            TRUE            TRUE            TRUE 
##  0.016602107211  0.033523641144  0.025673263853  0.000865614789 
##            TRUE            TRUE            TRUE            TRUE 
## -0.017530834254  0.025200238210 -0.036220284398 -0.031977285492 
##            TRUE            TRUE            TRUE            TRUE 
## -0.043639839730  0.000323186750 -0.024166406071 -0.016189488007 
##            TRUE            TRUE            TRUE            TRUE 
##  0.015315439510 -0.026072775668  0.000072740739  0.035527314657 
##            TRUE            TRUE            TRUE            TRUE 
## -0.012520543548  0.015441101771  0.004652701452 -0.001244710000 
##            TRUE            TRUE            TRUE            TRUE 
##  0.033690277174 -0.019479020991 -0.015987957507  0.019488965739 
##            TRUE            TRUE            TRUE            TRUE 
##  0.014201487137 -0.009014580512 -0.016376505500  0.028946772790 
##            TRUE            TRUE            TRUE            TRUE 
## -0.006994988374  0.002556678828  0.018618888113 -0.002756628008 
##            TRUE            TRUE            TRUE            TRUE 
## -0.003320948549  0.033951651867 -0.012434062892 -0.015257528043 
##            TRUE            TRUE            TRUE            TRUE 
##  0.004626732657 -0.022278555493 -0.006176461793  0.039937125295 
##            TRUE            TRUE            TRUE            TRUE 
## -0.013371047942  0.004691637075 -0.009402039151 -0.012462948345 
##            TRUE            TRUE            TRUE            TRUE 
## -0.011723522925 -0.026149627840 -0.024145146097  0.010232021520 
##            TRUE            TRUE            TRUE            TRUE 
## -0.023179767561 -0.025089475501  0.021392524100  0.028785337547 
##            TRUE            TRUE            TRUE            TRUE 
## -0.023155344946  0.007819875377  0.039895729841 -0.009475061013 
##            TRUE            TRUE            TRUE            TRUE 
## -0.006599587992 -0.012844116843 -0.007267467450  0.016587664485 
##            TRUE            TRUE            TRUE            TRUE 
##  0.009982840565 -0.003324322033 -0.026590886513 -0.023756598103 
##            TRUE            TRUE            TRUE            TRUE 
## -0.019637785560 -0.023423572026 -0.023576362718 -0.022298409849 
##            TRUE            TRUE            TRUE            TRUE 
## -0.004478439944  0.027530682799 -0.013088588978 -0.020700959977 
##            TRUE            TRUE            TRUE            TRUE 
## -0.003717543706 -0.033106945648 -0.002534364640  0.043445407601 
##            TRUE            TRUE            TRUE            TRUE 
##  0.018274757653  0.000157358950 -0.029785188868 -0.019916308793 
##            TRUE            TRUE            TRUE            TRUE 
##  0.061696831993 -0.036650754952 -0.005936241653 -0.009286848745 
##            TRUE            TRUE            TRUE            TRUE 
##  0.000186279544  0.002325595206  0.012267778267 -0.005242287979 
##            TRUE            TRUE            TRUE            TRUE 
## -0.029953476500 -0.022634071460  0.011546309618  0.003977055955 
##            TRUE            TRUE            TRUE            TRUE 
##  0.040250578140 -0.003011080031 -0.019311155045 -0.041743836567 
##            TRUE            TRUE            TRUE            TRUE 
##  0.028050691229  0.027806675920 -0.000811639052 -0.010080109340 
##            TRUE            TRUE            TRUE            TRUE 
##  0.033714559227 -0.029250034903 -0.023133101039  0.005387277490 
##            TRUE            TRUE            TRUE            TRUE 
##  0.009601285522  0.050900314229 -0.004575076191 -0.016271962652 
##            TRUE            TRUE            TRUE            TRUE 
##  0.037481194147  0.011446405309 -0.014779371893 -0.005943972553 
##            TRUE            TRUE            TRUE            TRUE 
##  0.005121088556  0.025075173336 -0.026094035642  0.005854399537 
##            TRUE            TRUE            TRUE            TRUE 
## -0.019071391732  0.000558311524 -0.004542606412 -0.005567372314 
##            TRUE            TRUE            TRUE            TRUE 
##  0.058510963347 -0.011752759782  0.018272649226 -0.018562979652 
##            TRUE            TRUE            TRUE            TRUE 
## -0.005712045561 -0.024141948315 -0.027965862174  0.027954160403 
##            TRUE            TRUE            TRUE            TRUE 
##  0.062017207507 -0.048568218039  0.002259601435  0.050293649442 
##            TRUE            TRUE            TRUE            TRUE 
## -0.000817648070 -0.012927153735 -0.009653363674 -0.004433003338 
##            TRUE            TRUE            TRUE            TRUE 
##  0.008333593666 -0.047398181503 -0.032460009900  0.039699364987 
##            TRUE            TRUE            TRUE            TRUE 
##  0.049823259333  0.009597982320 -0.019112681764 -0.014825757292 
##            TRUE            TRUE            TRUE            TRUE 
## -0.005827552231 -0.005396414008  0.029264547911 -0.008149141426 
##            TRUE            TRUE            TRUE            TRUE 
## -0.014923096348 -0.027340045839 -0.003962542947  0.005620785803 
##            TRUE            TRUE            TRUE            TRUE 
##  0.005479169776  0.016774365714 -0.012822892009 -0.033004300383 
##            TRUE            TRUE            TRUE            TRUE 
## -0.006415276314  0.023359475839 -0.006510050117 -0.006245899329 
##            TRUE            TRUE            TRUE            TRUE 
## -0.048032993793  0.009783980739  0.021427805116 -0.017068350747 
##            TRUE            TRUE            TRUE            TRUE 
##  0.008911970388 -0.016817342488 -0.025543138754 -0.016623788871 
##            TRUE            TRUE            TRUE            TRUE 
##  0.002719941374 -0.030947072820  0.016530772091 -0.019941609920 
##            TRUE            TRUE            TRUE            TRUE 
## -0.007233205508 -0.019385582526 -0.028182924755 -0.019684768346 
##            TRUE            TRUE            TRUE            TRUE 
## -0.027219197820 -0.059894161874 -0.026186525316 -0.003876413696 
##            TRUE            TRUE            TRUE            TRUE 
##  0.053979707302 -0.006299137116  0.004196648648  0.032533418308 
##            TRUE            TRUE            TRUE            TRUE 
## -0.028725915041 -0.015171961039 -0.000727512807 -0.007942374998 
##            TRUE            TRUE            TRUE            TRUE 
##  0.008570651164 -0.010159315922  0.026239025153  0.050056978488 
##            TRUE            TRUE            TRUE            TRUE 
##  0.015330936450 -0.009679894716 -0.001987298061  0.039100501380 
##            TRUE            TRUE            TRUE            TRUE 
## -0.033013577463 -0.015481688995  0.041815171687  0.008006576606 
##            TRUE            TRUE            TRUE            TRUE 
## -0.004221141544 -0.009581712290 -0.004652631171 -0.001425191369 
##            TRUE            TRUE            TRUE            TRUE 
## -0.029835158593 -0.016860986932 -0.023230158971  0.040543684661 
##            TRUE            TRUE            TRUE            TRUE 
##  0.022568815638 -0.012302215911 -0.027056427240  0.013561368638 
##            TRUE            TRUE            TRUE            TRUE 
##  0.018063176983  0.010843711393 -0.008465335225  0.003815374728 
##            TRUE            TRUE            TRUE            TRUE 
##  0.002152177069 -0.018791041194  0.010758249810  0.022126994717 
##            TRUE            TRUE            TRUE            TRUE 
## -0.019027149901 -0.029601720561 -0.019546736645  0.004857183751 
##            TRUE            TRUE            TRUE            TRUE 
##  0.001215543424 -0.018377332636  0.010358351450  0.018415178905 
##            TRUE            TRUE            TRUE            TRUE 
## -0.029859159523 -0.024276922797  0.034159718491 -0.021914851800 
##            TRUE            TRUE            TRUE            TRUE 
## -0.029233940576 -0.019508960657  0.014040614141 -0.001528152897 
##            TRUE            TRUE            TRUE            TRUE 
## -0.004618966617 -0.029370742361 -0.001042933517  0.019270321838 
##            TRUE            TRUE            TRUE            TRUE 
##  0.027297455610  0.009499589050 -0.010939504269 -0.022392972809 
##            TRUE            TRUE            TRUE            TRUE 
##  0.007434876570  0.005277639276  0.005941969547  0.009347255184 
##            TRUE            TRUE            TRUE            TRUE 
## -0.007188928536  0.009859848978 -0.011752548939 -0.016064985381 
##            TRUE            TRUE            TRUE            TRUE 
## -0.000424145273 -0.007365720157  0.004797444980  0.019659537500 
##            TRUE            TRUE            TRUE            TRUE 
##  0.028824484013 -0.028302999684 -0.017658253538  0.015935879355 
##            TRUE            TRUE            TRUE            TRUE 
## -0.009627570581  0.005039984389  0.011498237478 -0.015533626585 
##            TRUE            TRUE            TRUE            TRUE 
## -0.007709288370 -0.006937885137 -0.015142372777  0.023518134986 
##            TRUE            TRUE            TRUE            TRUE 
##  0.005004281689 -0.024707393351  0.008142745863  0.012067301980 
##            TRUE            TRUE            TRUE            TRUE 
## -0.009295774420  0.014254619503  0.008645535470 -0.035764899262 
##            TRUE            TRUE            TRUE            TRUE 
##  0.008091686784 -0.005560098240  0.004114982234  0.002526141774 
##            TRUE            TRUE            TRUE            TRUE 
##  0.017360016510  0.022858337833 -0.012568826531 -0.023665830312 
##            TRUE            TRUE            TRUE            TRUE 
## -0.025485227287  0.033608189075  0.023550042518 -0.025953719812 
##            TRUE            TRUE            TRUE            TRUE 
## -0.022286145831 -0.010363411676 -0.016566299089  0.011409894378 
##            TRUE            TRUE            TRUE            TRUE 
##  0.002441347860  0.013589305298 -0.028821040248  0.005256976689 
##            TRUE            TRUE            TRUE            TRUE 
## -0.033603655957  0.000584807426 -0.022982348493 -0.007618801703 
##            TRUE            TRUE            TRUE            TRUE 
##  0.041962058782  0.007208396347  0.002432035640  0.010645484095 
##            TRUE            TRUE            TRUE            TRUE 
## -0.003592303130 -0.012401276849 -0.006117214988 -0.019380100615 
##            TRUE            TRUE            TRUE            TRUE 
## -0.000996056152  0.016707036605 -0.017736581609  0.043203852125 
##            TRUE            TRUE            TRUE            TRUE 
## -0.001389945494 -0.007632611901 -0.014082115017 -0.022766304986 
##            TRUE            TRUE            TRUE            TRUE 
##  0.000122218497  0.053405020327 -0.028607386291  0.019200040932 
##            TRUE            TRUE            TRUE            TRUE 
##  0.004427486286  0.031251775691 -0.008859611113  0.013294055209 
##            TRUE            TRUE            TRUE            TRUE 
##  0.024397032867  0.003854134649  0.035437109113  0.004893940665 
##            TRUE            TRUE            TRUE            TRUE 
##  0.010899830697  0.009463780928 -0.010203065787  0.010263226243 
##            TRUE            TRUE            TRUE            TRUE 
## -0.000682322184 -0.006298574868 -0.010406037046 -0.002117739424 
##            TRUE            TRUE            TRUE            TRUE 
##  0.002739163202 -0.008957898961 -0.021812417378  0.005992360957 
##            TRUE            TRUE            TRUE            TRUE 
##  0.047374110292 -0.006322997483 -0.028462572483 -0.003578492932 
##            TRUE            TRUE            TRUE            TRUE 
##  0.002213883705  0.017249816049 -0.028871466799 -0.001052140315 
##            TRUE            TRUE            TRUE            TRUE 
##  0.073459571664 -0.019676123794  0.001331260937 -0.021557613951 
##            TRUE            TRUE            TRUE            TRUE 
## -0.016556038077 -0.004141302434 -0.023155134103  0.023100385276 
##            TRUE            TRUE            TRUE            TRUE 
##  0.041440820437  0.010346333415 -0.022584066595  0.035221733274 
##            TRUE            TRUE            TRUE            TRUE 
##  0.040116657872 -0.033208255575 -0.025474404028 -0.024080487662 
##            TRUE            TRUE            TRUE            TRUE 
##  0.047522859831 -0.041119285288  0.006142340413  0.008830479677 
##            TRUE            TRUE            TRUE            TRUE 
##  0.004773057505  0.024316315245  0.013281474926 -0.002144551590 
##            TRUE            TRUE            TRUE            TRUE 
## -0.007482035058  0.009468384327  0.002926391538  0.009143159431 
##            TRUE            TRUE            TRUE            TRUE 
## -0.007914051792  0.004536737956 -0.004515091437 -0.002889248079 
##            TRUE            TRUE            TRUE            TRUE 
## -0.014014153380 -0.015961672448 -0.033216970407  0.023912129750 
##            TRUE            TRUE            TRUE            TRUE 
##  0.009151312016 -0.036043457636 -0.021856870052  0.012834874904 
##            TRUE            TRUE            TRUE            TRUE 
## -0.027638880255 -0.001664427576 -0.007559449477  0.028680654137 
##            TRUE            TRUE            TRUE            TRUE 
## -0.009965481181  0.006329182203 -0.015174210028 -0.023171544695 
##            TRUE            TRUE            TRUE            TRUE 
## -0.022296828528 -0.023639510113 -0.004905009908  0.012924834465 
##            TRUE            TRUE            TRUE            TRUE 
## -0.015971863180 -0.019477193688  0.017365779545 -0.009388228953 
##            TRUE            TRUE            TRUE            TRUE 
## -0.022745853242  0.034590189045  0.023679324246  0.008339989228 
##            TRUE            TRUE            TRUE            TRUE 
## -0.018466765090 -0.016075984343  0.000511047614  0.051067653069 
##            TRUE            TRUE            TRUE            TRUE 
## -0.005404144908  0.001864833581 -0.001985857303 -0.035607680874 
##            TRUE            TRUE            TRUE            TRUE 
## -0.013546152821  0.016465691971  0.001868980155 -0.003748045620 
##            TRUE            TRUE            TRUE 
##  0.010018929811 -0.022579533476  0.012336969820</code></pre>
<p>R value is supposed to vary between 0 and 1 (not between -1 and +1) but you can obtained negative values but they are always close to 0. R value close to 1 indicates high separation between levels of your factor (e.g. control vs treatment samples), while R value close to 0 indicate no separation between levels of your factor.</p>
</div>
